version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/cache
    versions:
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/console
    versions:
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/yaml
    versions:
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/css-selector
    versions:
    - 5.2.4
  - dependency-name: symfony/dom-crawler
    versions:
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.4
