services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: amoscato
        ports:
            - 5432:5432
        volumes:
            - amoscato_pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10

volumes:
    amoscato_pg_data:
