services:
    # Commands
    amoscato.command.load_stream_items:
        class: Amoscato\Bundle\AppBundle\Command\LoadStreamItemsCommand
        arguments:
            -
                - '@amoscato.stream_source.flickr'
                - '@amoscato.stream_source.lastfm'
        tags:
            - { name: console.command }

    # Database Connections
    amoscato.database:
        class: PDO
        arguments:
            - 'pgsql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - %database_user%
            - %database_password%

    # Stream Sources
    amoscato.stream_source:
        abstract: true
        arguments:
            - '@amoscato.database'
    amoscato.stream_source.flickr:
        parent: amoscato.stream_source
        class: Amoscato\Bundle\AppBundle\Stream\Source\FlickrSource
        arguments:
            - '@integration.flickr_client'
        calls:
            - [setUserId, [%flickr_user_id%]]
            - [setPhotoUri, [%flickr_photo_uri%]]
    amoscato.stream_source.lastfm:
        parent: amoscato.stream_source
        class: Amoscato\Bundle\AppBundle\Stream\Source\LastfmSource
        arguments:
            - '@integration.lastfm_client'
        calls:
            - [setUser, [%lastfm_user%]]
