services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $currentSources: !tagged amoscato.current_source
      $streamSources: !tagged amoscato.stream_source

  Amoscato\Bundle\AppBundle\:
    resource: '../../*'

  Amoscato\Database\PDOFactory:
    arguments:
    - pgsql:host=%database_host%;port=%database_port%;dbname=%database_name%
    - '%database_user%'
    - '%database_password%'

  Amoscato\Bundle\AppBundle\Ftp\FtpClient:
    arguments:
    - '%ftp_host%'
    - '%ftp_user%'
    - '%ftp_password%'
    - '%ftp_directory%'

  # Current Sources
  Amoscato\Bundle\AppBundle\Current\AthleticActivitySource:
    arguments:
      $activityUri: '%strava_activity_uri%'

  Amoscato\Bundle\AppBundle\Current\BookSource:
    arguments:
      $userId: '%goodreads_user_id%'

  Amoscato\Bundle\AppBundle\Current\DrinkSource:
    arguments:
      $username: '%untappd_username%'

  Amoscato\Bundle\AppBundle\Current\MusicSource:
    arguments:
      $user: '%lastfm_user%'

  Amoscato\Bundle\AppBundle\Current\VideoSource:
    arguments:
      $youTubePlaylistId: '%youtube_playlist_id%'
      $youTubeVideoUri: '%youtube_video_uri%'

  # Stream Sources
  Amoscato\Bundle\AppBundle\Stream\Source\FlickrSource:
    arguments:
      $userId: '%flickr_user_id%'
      $photoUri: '%flickr_photo_uri%'
    calls:
    - [setWeight, [2]]

  Amoscato\Bundle\AppBundle\Stream\Source\GitHubSource:
    arguments:
      $username: '%github_username%'
    calls:
    - [setWeight, [3]]

  Amoscato\Bundle\AppBundle\Stream\Source\GoodreadsSource:
    arguments:
      $userId: '%goodreads_user_id%'

  Amoscato\Bundle\AppBundle\Stream\Source\LastfmSource:
    arguments:
      $user: '%lastfm_user%'
    calls:
    - [setWeight, [8]]

  Amoscato\Bundle\AppBundle\Stream\Source\TwitterSource:
    class:
    arguments:
      $screenName: '%twitter_screen_name%'
      $statusUri: '%twitter_status_uri%'
    calls:
    - [setWeight, [2]]

  Amoscato\Bundle\AppBundle\Stream\Source\UntappdSource:
    arguments:
      $username: '%untappd_username%'

  Amoscato\Bundle\AppBundle\Stream\Source\YouTubeSource:
    arguments:
      $playlistId: '%youtube_playlist_id%'
      $videoUri: '%youtube_video_uri%'
