services:

  # Commands
  amoscato.command.load_stream_items:
    class: Amoscato\Bundle\AppBundle\Command\LoadStreamItemsCommand
    calls:
    - [setSourceCollection, ['@amoscato.stream_source.collection']]
    tags:
    - { name: console.command }

  amoscato.command.cache_stream:
    class: Amoscato\Bundle\AppBundle\Command\CacheStreamCommand
    arguments:
    - '@amoscato.stream_aggregator'
    - '@amoscato.ftp_client'
    tags:
    - { name: console.command }

  amoscato.command.load_current_items:
    class: Amoscato\Bundle\AppBundle\Command\LoadCurrentItemsCommand
    arguments:
    - '@amoscato.ftp_client'
    calls:
    - [setSourceCollection, ['@amoscato.current_source.collection']]
    tags:
    - { name: console.command }

  # Database Connections
  amoscato.database:
    class: Amoscato\Database\PDOFactory
    arguments:
    - pgsql:host=%database_host%;port=%database_port%;dbname=%database_name%
    - %database_user%
    - %database_password%

  # FTP Client
  amoscato.ftp_client:
    class: Amoscato\Bundle\AppBundle\Ftp\FtpClient
    arguments:
    - %ftp_host%
    - %ftp_user%
    - %ftp_password%
    - %ftp_directory%

  # Controllers
  amoscato.controller.stream:
    class: Amoscato\Bundle\AppBundle\Controller\StreamController
    arguments:
    - '@amoscato.stream_aggregator'

  # Current Sources
  amoscato.current_source.collection:
    class: Amoscato\Bundle\AppBundle\Source\SourceCollection

  amoscato.current_source.book:
    class: Amoscato\Bundle\AppBundle\Current\BookSource
    arguments:
    - '@integration.goodreads_client'
    calls:
    - [setUserId, [%goodreads_user_id%]]
    tags:
    - { name: amoscato.current_source }

  amoscato.current_source.drink:
    class: Amoscato\Bundle\AppBundle\Current\DrinkSource
    arguments:
    - '@integration.untappd_client'
    calls:
    - [setUsername, [%untappd_username%]]
    tags:
    - { name: amoscato.current_source }

  amoscato.current_source.food:
    class: Amoscato\Bundle\AppBundle\Current\FoodSource
    arguments:
    - '@integration.foodspotting_client'
    calls:
    - [setPersonId, [%foodspotting_person_id%]]
    - [setReviewUri, [%foodspotting_review_uri%]]
    tags:
    - { name: amoscato.current_source }

  amoscato.current_source.music:
    class: Amoscato\Bundle\AppBundle\Current\MusicSource
    arguments:
    - '@integration.lastfm_client'
    calls:
    - [setUser, [%lastfm_user%]]
    tags:
    - { name: amoscato.current_source }

  amoscato.stream_source.video:
    class: Amoscato\Bundle\AppBundle\Current\VideoSource
    arguments:
    - '@integration.youtube_client'
    - '@integration.vimeo_client'
    calls:
    - [setYouTubePlaylistId, [%youtube_playlist_id%]]
    - [setYouTubeVideoUri, [%youtube_video_uri%]]
    tags:
    - { name: amoscato.current_source }

  # Stream Aggregator
  amoscato.stream_aggregator:
    class: Amoscato\Bundle\AppBundle\Stream\StreamAggregator
    arguments:
    - '@amoscato.database'
    calls:
    - [setSourceCollection, ['@amoscato.stream_source.collection']]

  # Stream Sources
  amoscato.stream_source.collection:
    class: Amoscato\Bundle\AppBundle\Source\SourceCollection

  amoscato.stream_source:
    abstract: true
    arguments:
    - '@amoscato.database'
    - '@amoscato.ftp_client'

  amoscato.stream_source.flickr:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\FlickrSource
    arguments:
    - '@integration.flickr_client'
    calls:
    - [setUserId, [%flickr_user_id%]]
    - [setPhotoUri, [%flickr_photo_uri%]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.foodspotting:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\FoodspottingSource
    arguments:
    - '@integration.foodspotting_client'
    calls:
    - [setPersonId, [%foodspotting_person_id%]]
    - [setReviewUri, [%foodspotting_review_uri%]]
    - [setWeight, [1]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.github:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\GitHubSource
    arguments:
    - '@integration.github_client'
    calls:
    - [setUsername, [%github_username%]]
    - [setWeight, [3]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.goodreads:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\GoodreadsSource
    arguments:
    - '@integration.goodreads_client'
    calls:
    - [setUserId, [%goodreads_user_id%]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.lastfm:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\LastfmSource
    arguments:
    - '@integration.lastfm_client'
    calls:
    - [setUser, [%lastfm_user%]]
    - [setWeight, [8]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.twitter:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\TwitterSource
    arguments:
    - '@integration.twitter_client'
    calls:
    - [setScreenName, [%twitter_screen_name%]]
    - [setStatusUri, [%twitter_status_uri%]]
    - [setWeight, [2]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.untappd:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\UntappdSource
    arguments:
    - '@integration.untappd_client'
    calls:
    - [setUsername, [%untappd_username%]]
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.vimeo:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\VimeoSource
    arguments:
    - '@integration.vimeo_client'
    tags:
    - { name: amoscato.stream_source }

  amoscato.stream_source.youtube:
    parent: amoscato.stream_source
    class: Amoscato\Bundle\AppBundle\Stream\Source\YouTubeSource
    arguments:
    - '@integration.youtube_client'
    calls:
    - [setPlaylistId, [%youtube_playlist_id%]]
    - [setVideoUri, [%youtube_video_uri%]]
    tags:
    - { name: amoscato.stream_source }
