# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  flickr_user_id: 91374488@N07
  github_client_id: d3acc90fe9b0b0064b6a
  github_username: namoscato
  goodreads_user_id: 16453252
  lastfm_user: namoscato
  untappd_username: namoscato
  twitter_screen_name: namoscato
  youtube_playlist_id: FLGxACpnRvOrg3YGcTP0rjTA
  ftp_directory: /data

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

#  # makes classes in src/ available to be used as services
#  # this creates a service per class whose id is the fully-qualified class name
#  Amoscato\:
#    resource: '../src/*'
#    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
#
#  # controllers are imported separately to make sure services can be injected
#  # as action arguments even if you don't extend any base controller class
#  Amoscato\Bundle\AppBundle\Controller\:
#    resource: '../src/Bundle/AppBundle/Controller'
#    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
