parameters:
    flickr_api_uri: 'https://api.flickr.com/services/rest/'
    flickr_photo_uri: 'https://www.flickr.com/photos/'
    foodspotting_api_uri: 'http://www.foodspotting.com/api/v1/'
    foodspotting_review_uri: 'http://www.foodspotting.com/reviews/'
    goodreads_api_uri: 'https://www.goodreads.com/'
    lastfm_api_uri: 'http://ws.audioscrobbler.com/2.0/'
    youtube_api_uri: 'https://www.googleapis.com/youtube/v3/'
    youtube_video_uri: 'https://youtu.be/'
