parameters:
  flickr_api_uri: https://api.flickr.com/services/rest/
  flickr_photo_uri: https://www.flickr.com/photos/
  github_api_uri: https://api.github.com/
  goodreads_api_uri: https://www.goodreads.com/
  lastfm_api_uri: http://ws.audioscrobbler.com/2.0/
  strava_activity_uri: https://www.strava.com/activities/
  strava_api_uri: https://www.strava.com/api/v3/
  twitter_api_uri: https://api.twitter.com/1.1/
  twitter_status_uri: https://twitter.com/
  untappd_api_uri: https://api.untappd.com/v4/
  vimeo_api_uri: https://api.vimeo.com/
  youtube_api_uri: https://www.googleapis.com/youtube/v3/
  youtube_video_uri: https://youtu.be/
