services:
  Amoscato\Client\ClientFactory:
    arguments:
    - GuzzleHttp\Client

  # Guzzle Clients
  Amoscato\Client\Client:
    abstract: true
    factory:
    - '@Amoscato\Client\ClientFactory'
    - getClient

  integration.client.flickr:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%flickr_api_uri%'

  integration.client.github:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%github_api_uri%'

  integration.client.goodreads:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%goodreads_api_uri%'

  integration.client.lastfm:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%lastfm_api_uri%'

  integration.client.strava:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%strava_api_uri%'

  integration.client.twitter:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%twitter_api_uri%'

  integration.client.untappd:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%untappd_api_uri%'

  integration.client.vimeo:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%vimeo_api_uri%'

  integration.client.youtube:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%youtube_api_uri%'

  # Integration Clients
  Amoscato\Bundle\IntegrationBundle\Client\FlickrClient:
    arguments:
    - '@integration.client.flickr'
    - '%env(AMOSCATO_FLICKR_API_KEY)%'

  Amoscato\Bundle\IntegrationBundle\Client\GitHubClient:
    arguments:
    - '@integration.client.github'
    - '%env(AMOSCATO_GITHUB_CLIENT_SECRET)%'
    - '%github_client_id%'

  Amoscato\Bundle\IntegrationBundle\Client\GoodreadsClient:
    arguments:
    - '@integration.client.goodreads'
    - '%env(AMOSCATO_GOODREADS_API_KEY)%'

  Amoscato\Bundle\IntegrationBundle\Client\LastfmClient:
    arguments:
    - '@integration.client.lastfm'
    - '%env(AMOSCATO_LASTFM_API_KEY)%'

  Amoscato\Bundle\IntegrationBundle\Client\StravaClient:
    arguments:
    - '@integration.client.strava'
    - '%env(AMOSCATO_STRAVA_ACCESS_TOKEN)%'

  Amoscato\Bundle\IntegrationBundle\Client\TwitterClient:
    arguments:
    - '@integration.client.twitter'
    - '%env(AMOSCATO_TWITTER_BEARER_TOKEN)%'

  Amoscato\Bundle\IntegrationBundle\Client\UntappdClient:
    arguments:
    - '@integration.client.untappd'
    - '%env(AMOSCATO_UNTAPPD_CLIENT_SECRET)%'
    - '%env(AMOSCATO_UNTAPPD_CLIENT_ID)%'

  Amoscato\Bundle\IntegrationBundle\Client\VimeoClient:
    arguments:
    - '@integration.client.vimeo'
    - '%env(AMOSCATO_VIMEO_ACCESS_TOKEN)%'

  Amoscato\Bundle\IntegrationBundle\Client\YouTubeClient:
    arguments:
    - '@integration.client.youtube'
    - '%env(AMOSCATO_YOUTUBE_API_KEY)%'
