services:
    # Client Factory
    integration.client.factory:
        class: Amoscato\Client\ClientFactory
        arguments:
            - GuzzleHttp\Client

    # Guzzle Clients
    integration.client:
        abstract: true
        class: Amoscato\Client\Client
        factory:
            - '@integration.client.factory'
            - getClient
    integration.client.flickr:
        parent: integration.client
        arguments:
            - base_uri: %flickr_api_uri%
    integration.client.foodspotting:
        parent: integration.client
        arguments:
            - base_uri: %foodspotting_api_uri%
    integration.client.goodreads:
        parent: integration.client
        arguments:
            - base_uri: %goodreads_api_uri%
    integration.client.lastfm:
        parent: integration.client
        arguments:
            - base_uri: %lastfm_api_uri%

    # Integration Clients
    integration.flickr_client:
        class: Amoscato\Bundle\IntegrationBundle\Client\FlickrClient
        arguments:
            - '@integration.client.flickr'
            - %flickr_api_key%
    integration.foodspotting_client:
        class: Amoscato\Bundle\IntegrationBundle\Client\FoodspottingClient
        arguments:
            - '@integration.client.foodspotting'
            - %foodspotting_api_key%
    integration.goodreads_client:
        class: Amoscato\Bundle\IntegrationBundle\Client\GoodreadsClient
        arguments:
            - '@integration.client.goodreads'
            - %goodreads_api_key%
    integration.lastfm_client:
        class: Amoscato\Bundle\IntegrationBundle\Client\LastfmClient
        arguments:
            - '@integration.client.lastfm'
            - %lastfm_api_key%
