services:
  Amoscato\Client\ClientFactory:
    arguments:
    - GuzzleHttp\Client

  # Guzzle Clients
  Amoscato\Client\Client:
    abstract: true
    factory:
    - '@Amoscato\Client\ClientFactory'
    - getClient

  integration.client.flickr:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%flickr_api_uri%'

  integration.client.github:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%github_api_uri%'

  integration.client.goodreads:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%goodreads_api_uri%'

  integration.client.lastfm:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%lastfm_api_uri%'

  integration.client.strava:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%strava_api_uri%'

  integration.client.twitter:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%twitter_api_uri%'

  integration.client.untappd:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%untappd_api_uri%'

  integration.client.vimeo:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%vimeo_api_uri%'

  integration.client.youtube:
    parent: Amoscato\Client\Client
    arguments:
    - base_uri: '%youtube_api_uri%'

  # Integration Clients
  Amoscato\Bundle\IntegrationBundle\Client\FlickrClient:
    arguments:
    - '@integration.client.flickr'
    - '%flickr_api_key%'

  Amoscato\Bundle\IntegrationBundle\Client\GitHubClient:
    arguments:
    - '@integration.client.github'
    - '%github_client_secret%'
    - '%github_client_id%'

  Amoscato\Bundle\IntegrationBundle\Client\GoodreadsClient:
    arguments:
    - '@integration.client.goodreads'
    - '%goodreads_api_key%'

  Amoscato\Bundle\IntegrationBundle\Client\LastfmClient:
    arguments:
    - '@integration.client.lastfm'
    - '%lastfm_api_key%'

  Amoscato\Bundle\IntegrationBundle\Client\StravaClient:
    arguments:
    - '@integration.client.strava'
    - '%strava_access_token%'

  Amoscato\Bundle\IntegrationBundle\Client\TwitterClient:
    arguments:
    - '@integration.client.twitter'
    - '%twitter_bearer_token%'

  Amoscato\Bundle\IntegrationBundle\Client\UntappdClient:
    arguments:
    - '@integration.client.untappd'
    - '%untappd_client_secret%'
    - '%untappd_client_id%'

  Amoscato\Bundle\IntegrationBundle\Client\VimeoClient:
    arguments:
    - '@integration.client.vimeo'
    - '%vimeo_access_token%'

  Amoscato\Bundle\IntegrationBundle\Client\YouTubeClient:
    arguments:
    - '@integration.client.youtube'
    - '%youtube_api_key%'
