name: current
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
    - name: Install dependencies
      run: composer install --no-interaction
    - name: Load current
      run: bin/console amoscato:current:load -v
      env:
        SYMFONY_ENV: ${{ secrets.SYMFONY_ENV }}
        APP_ENV: ${{ secrets.APP_ENV }}
        APP_SECRET: ${{ secrets.APP_SECRET }}

        AMOSCATO_GOODREADS_API_KEY: ${{ secrets.AMOSCATO_GOODREADS_API_KEY }}
        AMOSCATO_LASTFM_API_KEY: ${{ secrets.AMOSCATO_LASTFM_API_KEY }}
        AMOSCATO_UNTAPPD_CLIENT_ID: ${{ secrets.AMOSCATO_UNTAPPD_CLIENT_ID }}
        AMOSCATO_UNTAPPD_CLIENT_SECRET: ${{ secrets.AMOSCATO_UNTAPPD_CLIENT_SECRET }}
        AMOSCATO_VIMEO_ACCESS_TOKEN: ${{ secrets.AMOSCATO_VIMEO_ACCESS_TOKEN }}
        AMOSCATO_YOUTUBE_API_KEY: ${{ secrets.AMOSCATO_YOUTUBE_API_KEY }}

        AMOSCATO_STRAVA_CLIENT_ID: ${{ secrets.AMOSCATO_STRAVA_CLIENT_ID }}
        AMOSCATO_STRAVA_CLIENT_SECRET: ${{ secrets.AMOSCATO_STRAVA_CLIENT_SECRET }}
        AMOSCATO_STRAVA_REFRESH_TOKEN: ${{ secrets.AMOSCATO_STRAVA_REFRESH_TOKEN }}
        REDIS_URL: ${{ secrets.REDIS_URL }}

        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AMOSCATO_S3_BUCKET_CACHE: ${{ secrets.AMOSCATO_S3_BUCKET_CACHE }}
